[package]
name = "pathtracer"
version = "0.1.0"
authors = ["Francisco Soto <ebobby@ebobby.org>"]
edition = "2021"

[dependencies]
image = "0.24.5"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
threadpool = "1.8.1"
indicatif = "0.17.3"
