[package]
name = "pathtracer"
version = "0.1.0"
authors = ["Francisco Soto <ebobby@ebobby.org>"]
edition = "2018"

[dependencies]
image = "0.24.3"
rand = "0.7.1"
rand_xoshiro = "0.4.0"
threadpool = "1.8.1"
indicatif = "0.15.0"
